-- MySQL Script generated by MySQL Workbench
-- 03/19/16 15:37:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema vesna-15-yii2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `vesna-15-yii2` ;

-- -----------------------------------------------------
-- Schema vesna-15-yii2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vesna-15-yii2` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table ``vesna-15-yii2`.`events_format`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vesna-15-yii2`.`events_format` ;

CREATE TABLE IF NOT EXISTS `vesna-15-yii2`.`events_format` (
  `id` INT NOT NULL,
  `events_format_description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `vesna-15-yii2`.`events_format` (`id` ASC);

USE `vesna-15-yii2` ;

-- -----------------------------------------------------
-- Table `vesna-15-yii2`.`events_ru`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vesna-15-yii2`.`events_ru` ;

CREATE TABLE IF NOT EXISTS `vesna-15-yii2`.`events_ru` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `title_ru` VARCHAR(255) CHARACTER SET 'latin2' NULL DEFAULT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `event_type` INT(11) NOT NULL,
  `public_access` TINYINT(1) NOT NULL DEFAULT 0,
  `preview_image` VARCHAR(255) NULL DEFAULT NULL,
  `events_format_id` INT NOT NULL,
  `format` TINYINT(1) NULL DEFAULT 0,
  `preview_ru` TEXT NOT NULL,
  `city_ru` VARCHAR(255) NULL DEFAULT NULL,
  `address_ru` VARCHAR(255) NULL DEFAULT NULL,
  `place_ru` VARCHAR(255) NULL DEFAULT NULL,
  `place_details_ru` TEXT NULL DEFAULT NULL,
  `map_url` VARCHAR(255) NULL DEFAULT NULL,
  `video_url` VARCHAR(255) NULL DEFAULT NULL,
  `video_details` TEXT NULL DEFAULT NULL,
  `tag` VARCHAR(255) NULL DEFAULT NULL,
  `started_at` INT(10) UNSIGNED NULL DEFAULT NULL,
  `ending_at` INT(10) UNSIGNED NULL DEFAULT NULL,
  `timezone` VARCHAR(255) NOT NULL,
  `contact_person` VARCHAR(255) NULL DEFAULT NULL,
  `contact_phone` VARCHAR(126) NULL DEFAULT NULL,
  `contact_email` VARCHAR(255) NULL DEFAULT NULL,
  `contact_skype` VARCHAR(255) NULL DEFAULT NULL,
  `contact_details_ru` TEXT NULL DEFAULT NULL,
  `cost` VARCHAR(255) NULL DEFAULT NULL,
  `cost_free_status` TINYINT(4) NOT NULL DEFAULT 0,
  `cost_details_ru` TEXT NULL DEFAULT NULL,
  `end_registration_time` INT(10) UNSIGNED NULL DEFAULT NULL,
  `registration_format` TINYINT(2) NULL DEFAULT 0,
  `organizer` VARCHAR(255) NULL DEFAULT NULL,
  `coorganizer` VARCHAR(255) NULL DEFAULT NULL,
  `coorganizer_preview_image` VARCHAR(255) NULL DEFAULT NULL,
  `coorganizer_name` VARCHAR(255) NULL DEFAULT NULL,
  `coorganizer_url` VARCHAR(255) NULL DEFAULT NULL,
  `coorganizer_description` TEXT NULL DEFAULT NULL,
  `sponsor` VARCHAR(255) NULL DEFAULT NULL,
  `sponsor_preview_image` VARCHAR(255) NULL DEFAULT NULL,
  `sponsor_name` VARCHAR(255) NULL DEFAULT NULL,
  `sponsor_url` VARCHAR(255) NULL DEFAULT NULL,
  `sponsor_description` TEXT NULL DEFAULT NULL,
  `event_url_vk` VARCHAR(255) NULL DEFAULT NULL,
  `event_url_fb` VARCHAR(255) NULL DEFAULT NULL,
  `sponsor_url_twitter` VARCHAR(255) NULL DEFAULT NULL,
  `sponsor_url_google` VARCHAR(255) NULL DEFAULT NULL,
  `sponsor_url_linkedin` VARCHAR(255) NULL DEFAULT NULL,
  `sponsor_url_youtube` VARCHAR(255) NULL DEFAULT NULL,
  `event_program` TEXT NULL DEFAULT NULL,
  `event_speakers` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `user_id`),
  CONSTRAINT `fk_events_ru_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `vesna-15-yii2`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_events_ru_events_format`
    FOREIGN KEY (`events_format_id`)
    REFERENCES `vesna-15-yii2`.`events_format` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE UNIQUE INDEX `id_UNIQUE` ON `vesna-15-yii2`.`events_ru` (`id` ASC);

CREATE UNIQUE INDEX `preview_image_UNIQUE` ON `vesna-15-yii2`.`events_ru` (`preview_image` ASC);

CREATE INDEX `fk_events_ru_user1_idx` ON `vesna-15-yii2`.`events_ru` (`user_id` ASC);

CREATE INDEX `fk_events_ru_events_format1_idx` ON `vesna-15-yii2`.`events_ru` (`events_format_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
